feat(add the possibility to set identified visitor)
ovh-ux/ng-at-internet pull request #2
Opened 2017-08-28 18:02 UTC by whispyy

- add a config object identifiedVisitor
- add a function to set it
- call the setIdentifiedVisitor with config if set in the module.

- implement README.me
- implement test case

2017-08-30 12:04 UTC, Jisay requested changes

2017-08-30 12:04 UTC, Jisay commented on bower.json
> +  "version": "2.3.0",
do not increment version in bower.json (and package.json). This will be done automatically when we will launch the release

2017-08-30 12:04 UTC, Jisay commented on package.json
> +  "version": "2.3.0",
the same so :-) do not increment the version

2017-08-30 12:04 UTC, Jisay commented on src/ng-at-internet.provider.js
> +                            if (config.identifiedVisitor !== {}) {
this test is always true. {} === {} is false. This is reference comparison.
You can use : 
- lodash ```_.isEmpty(config.identifiedVisitor)```
- or angular ```angular.isEqual()```
for making this kind of test

2017-08-30 12:04 UTC, Jisay commented on src/ng-at-internet.provider.js
> +                        if (config.identifiedVisitor !== {}) {
the same so !

2017-08-30 12:04 UTC, Jisay commented on src/ng-at-internet.provider.js
> +                        if (config.identifiedVisitor !== {}) {
the same so !

2017-10-12 01:00 UTC, whispyy commented
Will re-up a new one with updates.

2017-10-12 01:00 UTC, closed without merging