WIP : Add tracking delegation until config is set.
ovh-ux/ng-at-internet pull request #4
Opened 2017-10-12 01:46 UTC by whispyy

2017-10-16 14:08 UTC, tremblaymath requested changes

2017-10-16 14:08 UTC, tremblaymath commented on src/ng-at-internet.config.js
> +            _.forEach(trackPageRequestArgumentStack, function (trackPageArguments) {
You should name it trackPageRequestQueue because it's first in, first out

2017-10-16 14:08 UTC, tremblaymath commented on src/ng-at-internet.config.js
> +                limit: 30,
You should precise limit of what? e.g queueLimit

2017-10-16 14:08 UTC, tremblaymath commented on src/ng-at-internet.config.js
> +            settings.isDefaultConfigSet = true;
I don't why it's systematically settled to true. It's possible that config isn't done.  e.g /me promise not done or not configured in the manager..

2017-10-27 06:39 UTC, antleblanc commented
:candy: Please ref [commit-message-format](https://github.com/ovh-ux/ovh-ux-guidelines/blob/master/.github/CONTRIBUTING.md#commit-message-format).

2017-10-27 09:12 UTC, feoche approved these changes

2017-10-31 19:38 UTC, tremblaymath commented
You should update readme "provider.setDefaults" for a more complete example

2017-10-31 19:51 UTC, tremblaymath requested changes

2017-10-31 19:51 UTC, tremblaymath commented on src/ng-at-internet.config.js
> +        $provide.decorator("atInternet", function ($delegate) {
You should test decorator behavior
- No track before config is set
- Everything is tracked after config is set
- Exception raised after 30 tracks without config

2017-10-31 19:51 UTC, tremblaymath commented on src/ng-at-internet.config.js
> +            // Decorate trackPage to stack requests until At-internet default configuration is set
"to queue requests"

2017-11-08 16:13 UTC, Netnix approved these changes

2017-11-08 21:27 UTC, tremblaymath approved these changes
You should test decorator behavior in the futur

2017-11-09 19:12 UTC, merged